import "./globals.css";
<<<<<<< HEAD
// import { Inter } from "next/font/google";
import Providers from "@/utils/provider";
import React from "react";
import Head from "next/head";
=======
import { Inter } from "next/font/google";
import { AvatarProvider } from "@/context/AvatarContext";
>>>>>>> upstream/EunSu

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "모두의 게시판",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <Head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        />
      </Head>
      <body>
        <Providers>{children}</Providers>
      </body>
=======
      <AvatarProvider>
        <body className={inter.className}>
          {children}
          <div id="portal" />
        </body>
      </AvatarProvider>
>>>>>>> upstream/EunSu
    </html>
  );
}
